### PR TITLE
Update automated setup files

### PR DESCRIPTION
**Pull request by pigeonfresh**
Some files for the automated setup were outdated. This PR will update these files.

### CODE REVIEW

**Comment by ThaNarie** [comment]
Are these files the 'same' as in the skeleton? Does sound like a maintenance nightmare....

**Comment by pigeonfresh** [comment]
Well the thing was that they weren't anymore. I ran the automated setup and noticed these were outdated. Perhaps this script should be removed but that is something @larsvanbraam should decide.

**Comment by larsvanbraam** [comment]
Yeah it is a nightmare but I was still looking into a way to modify certain lines of code within a file (we need to modify some skeleton code to make page transitions work) but that was taking up too much time, so I left it like this for now! If anyone has some suggestions on this that would be great 😀

**Comment by ThaNarie** [comment]
I think I would rather have it that we add some documentation on how to do that manually, and only do an automatic approach once we figure out a better approach.

**Comment by pigeonfresh** [comment]
The old documentation had this explanation and at the bottom the lazy 'Use at your own risk' convert script. I couldn't find this page in the new wiki.

**Comment by larsvanbraam** [comment]
The new documentation still contains the details on the manual setup checkout this link: https://larsvanbraam.gitbook.io/vue-transition-component/examples/setup-page-transitioning it’s now categorized under page transitioning since that is what it does. You could use vue transition component without page transitions if you choose to. I’m not a big fan of removing the automated setup completely because it does make your life easier and you cannot make setup mistakes. I could look into updating the setup task to no longer require the skeleton files when I’m back from vacation 😀

**Comment by larsvanbraam** [comment]
I'll update the automated setup in the v2.x.x version of the vue-transition-component.

**Pull request merged**
